openai:
  model: "text-embedding-3-small"
  dimensions: 512
etl:
  note_weight: .4
  accord_decay: .85
  accord_weight: .6
  top_notes_weight: 0.25
  mid_notes_weight: 0.30
  base_notes_weight: 0.45
  batch_size: 2048
redis:
  key_prefix: "fragentic:"