openai:
  model: "text-embedding-3-large"
  dimensions: 1024
etl:
  note_weight: .4
  accord_decay: .90
  accord_weight: .6
  top_note_weight: 0.25
  mid_note_weight: 0.30
  base_note_weight: 0.45
  batch_size: 2048